[theme]
base = "light"
primaryColor = "#3563C2"
backgroundColor = "#E8F3FF"
secondaryBackgroundColor = "#F4F9FF"
textColor = "#1D2939"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
address = "localhost"
